--- #YAML:1.0
name: File-BOM
version: 0.11
author:
  - Matt Lawrence E<lt>mattlaw@cpan.orgE<gt>
abstract: Utilities for handling Byte Order Marks
license: perl
requires:
  Readonly: 0.06
  perl: 5.8.3
build_requires:
  Module::Build: 0.20
  Test::Exception: 0.20
  Test::More: 0.01
provides:
  File::BOM:
    file: lib/File/BOM.pm
    version: 0.11
generated_by: Module::Build version 0.2611
