--- #YAML:1.0
name: File-BOM
version: 0.08
author:
  - Matt Lawrence E<lt>mattlaw@cpan.orgE<gt>
abstract: Utilities for reading Byte Order Marks
license: perl
requires:
  perl: 5.8.0
build_requires:
  Module::Build: 0.20
  Test::Exception: 0.20
  Test::More: 0.01
provides:
  File::BOM:
    file: lib/File/BOM.pm
    version: 0.08
generated_by: Module::Build version 0.2608
