---
abstract: 'Utilities for handling Byte Order Marks'
author:
  - 'Matt Lawrence E<lt>mattlaw@cpan.orgE<gt>'
build_requires:
  Module::Build: '0.20'
  Test::Exception: '0.20'
  Test::More: '0.10'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4229, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-BOM
provides:
  File::BOM:
    file: lib/File/BOM.pm
    version: '0.18'
requires:
  Encode: '1.99'
  Readonly: '0.06'
  perl: v5.8.3
resources:
  Type: git
  Web: https://github.com/mattlaw/File-BOM
  license: http://dev.perl.org/licenses/
  repository: https://github.com/mattlaw/File-BOM.git
version: '0.18'
x_meta_spec:
  version: 2
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
